export { default as ClienteTableSkeleton } from './clienteTableSkeleton.svelte';
export { default as ZonaTableSkeleton } from './zonaTableSkeleton.svelte';
export { default as EmpleadoTableSkeleton } from './empleadoTableSkeleton.svelte';
export { default as CompraPolloTableSkeleton } from './compraPolloTableSkeleton.svelte';
export { default as ProveedorTableSkeleton } from './proveedorTableSkeleton.svelte';
export { default as VentaPolloTableSkeleton } from './ventaPolloTableSkeleton.svelte';
export { default as DespachoTableSkeleton } from './despachoTableSkeleton.svelte';
export { default as MarcaTableSkeleton } from './marcaTableSkeleton.svelte';
export { default as UnidadMedidaTableSkeleton } from './unidadMedidaTableSkeleton.svelte';
